### ISSUE TITLE
Handling of data stroed without channel dimension

### ISSUE THREAD

**Issue by AUdaltsova** [openclimatefix/ocf-data-sampler#44]
Currently all loaders assume the data they're opening has only one variable and a channel dimension. That's not always true for at least ECMWF (probably some other NWPs as well), importantly the new UK data is stored with variables unstacked.

I've recently had problems with .to_array() put into the loader slowing down batch creation twofold: that resolved after moving it out to [here](https://github.com/openclimatefix/ocf_datapipes/blob/9ec252eeee44937c12ab52699579bdcace76e72f/ocf_datapipes/utils/utils.py#L165) in combine_to_single_dataset, but I don't think it's a good long-term practice, it's very hacky and the function itself needs a rehaul. Also, this means the data is handled as a dataset along the way (not really an issue, I'm pretty sure everything before that minus maybe channel filtering supports datasets by default, but does mean halting the move towards exclusively dataArrays).

It's going to take some time before archives are redone with all data stacked, so this needs to be handled in the code in the meantime. I'm not sure what the best solution would be for this.

Thoughts?

**Comment by dfulu** [comment]
Personally I don't think we should support datasets which aren't a single variable with a channels dimension. Trying to support too many formats is one of the things that led to bloat in ocf_datapipes, particularly in loading PV data there. I think we should try to avoid that here

In this case I would propose that either:
 - We compile the new ECMWF data into a single zarr with the expected format. @zakwatts and I did this for the recent backtest
 - You make your own local branch of data-sampler with whatever changes you need. I have been doing this with ocf_datapipes quite long term in my GCP instance to extend the ECMWF in latitude (filling with 0s) so that it covers the Shetlands. When there have been changes to the main branch of ocf_datapipes I've just been merging it into my local branch. That's worked well for me and stopped me merging my very specific code into datapipes

**Comment by AUdaltsova** [comment]
Yeah I don't like the idea of supporting datasets either. If resaving ecmwf zarrs with channel dimension is feasible that'd be the best solution, I was just worried about size and archive bloating
